### PR TITLE
Reimplement `create_savefile_path`

### LINKED ISSUE #2: Heap corruption after save file path changes
When running version 6 from the hatchery, with some existing roms available:

```
rst:0x5 (DEEPSLEEP_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0148,len:5188
load:0x40078000,len:16020
load:0x40080400,len:4388
0x40080400: _init at ??:?

entry 0x40080674
I (237) psram: This chip is ESP32-D0WD
I (237) spiram: Found 64MBit SPI RAM device
I (238) spiram: SPI RAM mode: flash 80m sram 80m
I (240) spiram: PSRAM initialized, cache is in low/high (2-core) mode.
I (248) cpu_start: Pro cpu up.
I (251) cpu_start: Starting app cpu, entry point is 0x40081568
0x40081568: esp_ota_get_app_elf_sha256 at .../mch2022-esp32-app-gnuboy/esp-idf/components/app_update/esp_app_desc.c:97

I (0) cpu_start: App cpu up.
I (754) spiram: SPI SRAM memory test OK
I (761) cpu_start: Pro cpu start user code
I (761) cpu_start: cpu freq: 240000000
I (761) cpu_start: Application information:
I (764) cpu_start: Project name:     main
I (769) cpu_start: App version:      0.1
I (773) cpu_start: ELF file SHA256:  22d05acb5cfd16bb...
I (779) cpu_start: ESP-IDF:          v4.4.1
I (784) heap_init: Initializing. RAM available for dynamic allocation:
I (792) heap_init: At 3FFAE6E0 len 00001920 (6 KiB): DRAM
I (798) heap_init: At 3FFC0670 len 0001F990 (126 KiB): DRAM
I (804) heap_init: At 3FFE0440 len 00003AE0 (14 KiB): D/IRAM
I (810) heap_init: At 3FFE4350 len 0001BCB0 (111 KiB): D/IRAM
I (817) heap_init: At 4009899C len 00007664 (29 KiB): IRAM
I (823) spiram: Adding pool of 4095K of external SPI memory to heap allocator
I (831) spi_flash: detected chip: gd
I (835) spi_flash: flash io: qio
I (840) cpu_start: Starting scheduler on PRO CPU.
I (0) cpu_start: Starting scheduler on APP CPU.
I (849) spiram: Reserving pool of 32K of internal memory for DMA/internal allocations
I (859) hardware: LCD mode switch to ESP32
I (859) ili9341: reset
I (969) ili9341: sleep mode off
I (1619) gpio: GPIO[34]| InputEn: 1| OutputEn: 0| OpenDrain: 0| Pullup: 1| Pulldown: 0| Intr:2 
app_main: displayBuffer[0]=0x3ffcf558, [1]=0x3ffe4bbc
I (1709) main: SD card filesystem mounted
I (1709) gpio: GPIO[5]| InputEn: 0| OutputEn: 1| OpenDrain: 0| Pullup: 0| Pulldown: 0| Intr:0 
audio_init: sample_rate=32000
I (1719) I2S: APLL expected frequency is 16384000 Hz, real frequency is 16383999 Hz
I (1729) I2S: DMA Malloc info, datalen=blocksize=2048, dma_buf_count=6
I (1739) I2S: I2S0, MCLK output by GPIO0
Failed to read volume level from NVS
ROM filename: '/sd/games/Star Wars Episode I - Obi-Wan's Adventures.gbc'
Initialized. ROM@0x3f858afc
loader: rom.name='STAR WARS EBOWE?'
loader: mbc.type=MBC_MBC5, mbc.romsize=64 (1024K), mbc.ramsize=1 (8K)
ROM filename stored: '/sd/games/Star Wars Episode I - Obi-Wan's Adventures.gbc'
LOADING STATE
/sd/games/Star Wars Episode I - Obi-Wan's Adventures.sta
load_state: fopen load failed
LOADING SRAM

assert failed: block_trim_free heap_tlsf.c:377 (block_is_free(block) && "block must be free")


Backtrace:0x40081f46:0x3ffc42f00x40091629:0x3ffc4310 0x40097681:0x3ffc4330 0x4009685e:0x3ffc4450 0x40097281:0x3ffc4470 0x400820ed:0x3ffc4490 0x40082151:0x3ffc44b0 0x40097691:0x3ffc44d0 0x400d7b05:0x3ffc44f0 0x400d7c9b:0x3ffc4510 0x400d89a2:0x3ffc4530 0x401168c3:0x3ffc4590 0x400944c5:0x3ffc45b0 
0x40081f46: esp_vApplicationTickHook at .../mch2022-esp32-app-gnuboy/esp-idf/components/esp_system/freertos_hooks.c:36

0x40091629: esp_error_check_failed_print at .../mch2022-esp32-app-gnuboy/esp-idf/components/esp_system/esp_err.c:29

0x40097681: multi_heap_get_info_impl at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/multi_heap.c:377

0x4009685e: insert_free_block at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_tlsf.c:240
 (inlined by) block_insert at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_tlsf.c:269
 (inlined by) tlsf_add_pool at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_tlsf.c:689

0x40097281: mapping_insert at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_tlsf.c:157
 (inlined by) block_remove at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_tlsf.c:260
 (inlined by) block_merge_next at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_tlsf.c:367
 (inlined by) block_trim_used at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_tlsf.c:397
 (inlined by) tlsf_realloc at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_tlsf.c:943

0x400820ed: get_all_caps at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_private.h:61
 (inlined by) heap_caps_malloc_base at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_caps.c:134

0x40082151: heap_caps_malloc at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/heap_caps.c:167

0x40097691: multi_heap_get_info_impl at .../mch2022-esp32-app-gnuboy/esp-idf/components/heap/multi_heap.c:378

0x400d7b05: create_savefile_path at .../mch2022-esp32-app-gnuboy/main/main.c:437

0x400d7c9b: load_sram at .../mch2022-esp32-app-gnuboy/main/main.c:558

0x400d89a2: app_main at .../mch2022-esp32-app-gnuboy/main/main.c:1200

0x401168c3: main_task at .../mch2022-esp32-app-gnuboy/esp-idf/components/freertos/port/port_common.c:125 (discriminator 1)

0x400944c5: vListInsert at .../mch2022-esp32-app-gnuboy/esp-idf/components/freertos/list.c:182





ELF file SHA256: 22d05acb5cfd16bb

CPU halted.
```

(PR incoming)

### PR DESCRIPTION
**Pull request by ankon**
The existing implementation was fairly complex, and contained a memory corruption bug. Simplyfing
this (and in particular reducing allocations and related calculations) fixes the corruption as a
side-effect.

Fixes: #2
Together-with: @raugustijn

### CODE REVIEW

File: main/main.c [hunk 1]
```diff
@@ -403,64 +403,45 @@ char* system_util_GetFileName(const char* path)
...
+ * @param ext
+ * @return char*
+ */
 char* create_savefile_path(const char* rom_filename, const char* ext) {
     if (!rom_filename) return NULL;
     if (!ext) return NULL;
+    size_t ext_len = strlen(ext);
     
     int path_end = -1;
     int ext_pos = -1;
```
Comment (ankon) [inline main/main.c]: These are now unused and can go

Comment (ankon) [reply main/main.c]:
```suggestion
```

**Comment by renzenicolai** [comment]
Thank you, such improvements are very much appreciated. Sorry for the huge delay, I didn't get around to working on this app in quite a while.
